title: Bad Idea Bot
description: A FRC Robot, The Wrong Way.
theme: just-the-docs

url: https://el-8248.github.io/rebuilt-bad.idea.bot/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
